[package]
name = "daily_exp_sum"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
num-complex = "0.4.6"
plotters = "0.3.7"
tempfile = "3.13.0"
wallpaper = "3.2.0"

[target."cfg(windows)".dependencies]
windows = { version = "0.58.0", features = ["System_UserProfile", "Storage"] }